### ISSUE TITLE
question

### ISSUE THREAD

**Issue by git123java** [quartiq/minimq#118]
In no std project，how do I reference the appropriate stack and clock packages；Another question is that I tried to connect to an mqtt server of another computer, but I couldn't connect. Is it because I can only connect to the local mqtt server

**Comment by ryan-summers** [comment]
> In no std project，how do I reference the appropriate stack and clock packages

You have to provide them yourself. If you want to look at a reference design using `minimq` in deep embedded, check out https://github.com/quartiq/stabilizer/blob/master/src/net/mod.rs

* Quartiq [maintains a `stack` for `smoltcp`](https://github.com/quartiq/smoltcp-nal) that we use with minimq.
* Check out [`mono_clock`](https://docs.rs/mono-clock/0.1.1/mono_clock/struct.MonoClock.html) for a method to provide the `clock` if you use RTIC. Otherwise, implementing your own `embedded_time::Clock` is required 

> Another question is that I tried to connect to an mqtt server of another computer, but I couldn't connect. Is it because I can only connect to the local mqtt server

MQTT and this package do not care where your MQTT broker are. They can be local, or half way around the globe. This is all entirely managed by IP addresses and routing (i.e. the internet). If you can't connect to a broker on another machine, you need to look at your network infrastructure to make sure that packet routing is properly set up.

**Comment by git123java** [comment]
The local mqtt server and other mqtt servers need account and password for access, but actually the local server does not need the account and password to connect to it. Is the other connection failure caused by the password account

**Comment by ryan-summers** [comment]
Very likely. We do not support user/pass authentication currently (because it is insecure when transmitted over unencrypted channels), but would be open to accepting PRs for it!
